feat: user profile
atakowiec/simple-finance-manager pull request #12
Opened 2024-10-29 01:25 UTC by weronika28

Please approve if everything is ok. I have created a user profile and the ability to edit it.

2024-10-29 17:18 UTC, atakowiec commented on backend/src/main/java/pl/pollub/backend/auth/user/UsersRepository.java
> +@RestController
probably to delete

2024-10-29 17:19 UTC, atakowiec commented on frontend/src/main/java/pl/pollub/frontend/controller/LoginController.java
> +        screenService.switchTo("user");
change to 'home', starting screen after login should be home

2024-10-29 17:45 UTC, weronika28 commented
everything corrected

2024-10-29 17:48 UTC, atakowiec requested changes

2024-10-29 17:48 UTC, atakowiec commented on frontend/src/main/java/pl/pollub/frontend/controller/MainViewController.java
> +import pl.pollub.frontend.annotation.View;
u forgot to optimize imports

2024-10-29 17:54 UTC, atakowiec approved these changes
very cool

2024-10-29 17:55 UTC, merged

2024-12-07 16:36 UTC, atakowiec commented
![image](https://github.com/user-attachments/assets/0ad0b524-a624-4550-9b4e-f3291920288c)